language: python
python:
  - "2.7"
install:
  - pip install tox --use-mirrors
  - pip install coveralls
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
script:
  - tox
  - coverage run --source=hangman setup.py test
after_success:
  coveralls